version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    depends_on:
      - server
    networks:
      - mynetwork
    command: ["python", "client.py"]
    stdin_open: true
    tty: true

networks:
  mynetwork:
    driver: bridge
