version: '3.12'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "8000:8000"
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    depends_on:
      - server
    stdin_open: true
    tty: true
