#usa imagem do python
FROM python:3.11-slim

#define diretorio que vai trabalhar dentro do container
WORKDIR /app

#copia os arquivos necessários para dentro do container
COPY servidor_central.py .
COPY requirements.txt .

#instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

#expõe a porta usada pelo servidor
EXPOSE 9000

#comando para iniciar o servidor central
CMD ["python", "servidor_central.py"]
